### ISSUE TITLE
Fork on xdg_open

### ISSUE THREAD

**Issue by nblxxx** [kamiyaa/joshuto#124]
Is it possible to add a setting to enable this? or is there already a way around this that i missed?
Thanks!

**Comment by kamiyaa** [comment]
Nice, I never thought of this use case.
No way to do it at the moment, but I will add it shortly 👍

**Comment by DLFW** [comment]
Hey both!
Sorry, I don't really get what this Issue is about. Is it about opening files with `xdg-open` instead of joshuto's own file-opening logic?

I'm asking because in case it is, I would like to have the file-opener configurable. Ranger comes with [rifle](https://man.archlinux.org/man/rifle.1), which is a neat file-opener which can also provide multiple options per file. People changing from ranger over to joshuto and people who use both in parallel would benefit if they can use the same file-opener (and its configuration) from both file managers.

**Comment by kamiyaa** [comment]
> Sorry, I don't really get what this Issue is about. Is it about opening files with xdg-open instead of joshuto's own file-opening logic?

https://github.com/kamiyaa/joshuto/blob/main/src/commands/open_file.rs#L63

Yeah, the code currently does not fork when it opens via xdg.
Should a fairly straightforward change to add a new option in `joshuto.toml` and then check in the code

**Comment by kamiyaa** [comment]
Added in 1a50f82

You can enable it via
```toml
xdg_open_fork = true
```
in `joshuto.toml`

**Comment by nblxxx** [comment]
OMG you're a hero!
