### ISSUE TITLE
Various color requests

### ISSUE THREAD

**Issue by Beethoven-n** [kamiyaa/joshuto#156]
a few hiccups i have making the transition from ranger to joshuto:
<ul>
<li>
the background color doesn't show across entire panes, just across file text.
<details><summary>here's some pictures about it:</summary><img src="https://user-images.githubusercontent.com/44652883/156893864-67564dd8-b399-481c-86bb-e12e4595e9ab.png" height="80%" width="80%"/><img src="https://user-images.githubusercontent.com/44652883/156894010-cfc7327b-f8c6-4a78-8017-a5df7971b7be.png" height="80%" width="80%"/>
</details></li>

<li>the regular setting doesn't seem to do anything at all? my regular setting is set to the same as directories in the above joshuto pic</li>

<li>
there is no "hover" context like in ranger, so the hovered color is completely up to the foreground of whatever file is hovered:
<details>
<summary>an example:</summary>
<img src="https://user-images.githubusercontent.com/44652883/156894615-f638f785-0a15-4ce7-a1c3-161a360e18f0.png" height="80%" width="80%">
</details>
</li>
</ul>

i'm not sure what files to start in for changing these? also for some reason, only html let me be nice about putting the pictures down in a readable way lol

**Comment by kamiyaa** [comment]
>  the background color doesn't show across entire panes, just across file text. 

This is due to `joshuto` only drawing the text necessary to show the file name.
The selected file entry fills up the rest of the space with ' ' to make the background the same color.
See here: https://github.com/kamiyaa/joshuto/blob/main/src/ui/widgets/tui_dirlist_detailed.rs#L94

We could technically draw this space for all entries. I'm not sure if this will have a noticable performance impact though.

> the regular setting doesn't seem to do anything at all? my regular setting is set to the same as directories in the above joshuto pic

This is a bug. Looks like I didn't implement it xd.
See here: https://github.com/kamiyaa/joshuto/blob/main/src/util/style.rs#L47
These values should not just be `style::default()` and should be adding the fg, bg, modifier.

> there is no "hover" context like in ranger, so the hovered color is completely up to the foreground of whatever file is hovered: 

This could be implemented. Might be kind of tedious though because its currently hardcoded to just invert the colors on the current file entry.
See here: https://github.com/kamiyaa/joshuto/blob/main/src/ui/widgets/tui_dirlist_detailed.rs#L69

Because now we need to distinguish between the `bg`, `fg`, `modifier` not being present as either `inherit` or `default`

ie.
```toml
[hover]
# fg, bg assumed to be default or assumed to be inherit?
bold = true
```

**Comment by kamiyaa** [comment]
https://github.com/kamiyaa/joshuto/pull/163 fixes (1) and (2)
