### ISSUE TITLE
How does `--output-file` work?

### ISSUE THREAD

**Issue by ztlevi** [kamiyaa/joshuto#167]
Hi,

I see the `--last-dir` option is removed recently and merged into `--output-file`. But changing it to `--output-file` doesn't work for my zsh widget (for cd into directory after quit). Nothing is written to the output 

```
function joshuto-cd() {
  joshuto --output-file /tmp/joshuto-lastdir
  LASTDIR="$(cat /tmp/joshuto-lastdir)"
  [ "$LASTDIR" != "$(pwd)" ] && cd "$LASTDIR"
}
```

How should I use this argument properly?

**Comment by kamiyaa** [comment]
In addition to the removal of `--last-dir`, `quit` has also been changed as well.

Instead of `quit`, `force_quit`, and `quit_to_cwd`, everything has been combined into `quit`.

https://github.com/kamiyaa/joshuto/blob/main/src/key_command/impl_from_str.rs#L84

So if you want joshuto to output the current directory on quit, you can specify it via a quit command argument.

In addition, joshuto will also exit with a different exit code when this happens to help shell scripts understand what to do.

See new script here: https://github.com/kamiyaa/joshuto/blob/main/docs/configuration/keymap.toml.md

**Comment by ztlevi** [comment]
Thanks. It makes a lot more sense.
