### ISSUE TITLE
toml nightmare.

### ISSUE THREAD

**Issue by ben2talk** [kamiyaa/joshuto#181]
Tried out Joshuto - looks good.
Created keymap.toml
pasted contents of example
keymaps not set.

Why not install with a default keymap file?

**Comment by kamiyaa** [comment]
What do you mean by install with a default keymap file?

**Comment by notjedi** [comment]
@kamiyaa i'm not sure about the "install with a default keymap file" part but as far as the first one goes, copy pasting the keymap config file from [here](https://github.com/kamiyaa/joshuto/blob/main/config/keymap.toml) does not work. it says `Unmapped input: <KEY>`.

**Comment by kamiyaa** [comment]
> @kamiyaa i'm not sure about the "install with a default keymap file" part but as far as the first one goes, copy pasting the keymap config file from [here](https://github.com/kamiyaa/joshuto/blob/main/config/keymap.toml) does not work. it says `Unmapped input: <KEY>` (ig this is what he meant). i'm facing the same issue.
> 
> EDIT: this is fixed after updating to the latest version `v0.9.4`.

Ah I see. This was most likely due to the config file on github reflects the latest changes as opposed to the current release version (0.9.3).
I'm guessing you had 0.9.3 installed and not the latest git installed.

If you want to see what the configs looked like at the time of release, you can see here: https://github.com/kamiyaa/joshuto/tree/0.9.3
