### ISSUE TITLE
Bug: bat colored output not rendering correctly

### ISSUE THREAD

**Issue by fritzrehde** [kamiyaa/joshuto#213]
Maybe this is an already known bug (bottom of the readme says "File previews (in progress): Waiting for tui-rs to support parsing ANSI color codes"), but I thought I'd still create an issue just in case. 
Here are two screenshots showing the difference in color output between joshuto and standard bat:

![2022-10-24-09:52:44](https://user-images.githubusercontent.com/80471265/197476209-991eda06-cd46-4350-b701-0445b15c7b01.png)
![2022-10-24-09:52:54](https://user-images.githubusercontent.com/80471265/197476348-ef7c4836-403b-403e-99ff-489d2c9d7263.png)

**Comment by DLFW** [comment]
Hi!
I cannot reproduce this behavior.
![Screenshot_20221024_105424](https://user-images.githubusercontent.com/22507197/197489206-6db960b8-6e79-4468-b56b-bbc1f123dbd8.png)

The readme is not really up-to-date anymore. :smile: Joshuto is using `ansi-to-tui` since quite some time already to show colored previews.

1) The dependency to `ansi-to-tui` has just been upgraded a few days ago (#210). Are you using the latest from `main`?
2) How have you integrated `bat`? I used `try safepipe bat -pp --color always "$path" && { dump | trim; exit 5; }`. Similar for you?

**Comment by fritzrehde** [comment]
It works with the latest from `main`. I was previously using the AUR package.
