### ISSUE TITLE
quit to shell

### ISSUE THREAD

**Issue by alvaro17f** [kamiyaa/joshuto#239]
Hi, I've noticed that when you invoke Joshuto like this:

`alacritty -e joshuto`

the window gets closed after quit.

It should keep the terminal window open so whether you decide to cd on quit (quit --output-current-directory) or simply quit, you get your shell again.

`alacritty --hold -e joshuto` doesn't seems to work as expected.

Thanks in advance... I really love this project and use joshuto every day.

**Comment by pantosaur** [comment]
of course `alacritty --hold -e joshuto` doesn't do what you expect, because it is not spawning a shell at all. By default your terminal will spawn you default shell but `-e joshuto` overrides that. It is not really in the scope of a terminal program, i.e. joshuto to solve this problem, but can do this to get what you probably want:

alacritty -e bash --rcfile <(echo '. ~/.bashrc; joshuto')

**Comment by alvaro17f** [comment]
@pantosaur  thank you very much. That's exactly what I was looking for.
