### ISSUE TITLE
When symlinking configuration files will joshuto use the deafult config.

### ISSUE THREAD

**Issue by H4ckint0sh** [kamiyaa/joshuto#258]
I use mackup for my dotfiles and it breaks the configuration if I symlink joshuto configuration. I am not sure if this is a bug in joshuto or should I report it to mackup?

**Comment by DLFW** [comment]
Hi! I can say that my config files in `~/.config/joshuto` are also just symlinks to config files in my `dotfiles` repo. I do that since a long time and I never had any issues. There must be some other fishy thing there.  I have no idea what “mackup” is but your directory structure should easily be verifyable. Can you post a `pwd` and an `ls -al` from within your `~/.config/joshuto`?

**Comment by H4ckint0sh** [comment]
When symlinked it seems joshuto uses the default configuration.

````
> pwd
/Users/ali/.config/joshuto

> ls -al
total 16
drwxr-xr-x   9 ali  staff   288 Feb 23 00:03 .
drwxr-xr-x  12 ali  staff   384 Feb 22 12:28 ..
-rw-r--r--@  1 ali  staff  6148 Feb 22 22:00 .DS_Store
lrwxr-xr-x   1 ali  staff    58 Feb 23 00:03 bookmarks.toml -> /Users/ali/.dotfiles/mackup/.config/joshuto/bookmarks.toml
lrwxr-xr-x   1 ali  staff    56 Feb 23 00:03 joshuto.toml -> /Users/ali/.dotfiles/mackup/.config/joshuto/joshuto.toml
lrwxr-xr-x   1 ali  staff    55 Feb 23 00:03 keymap.toml -> /Users/ali/.dotfiles/mackup/.config/joshuto/keymap.toml
lrwxr-xr-x   1 ali  staff    57 Feb 23 00:03 mimetype.toml -> /Users/ali/.dotfiles/mackup/.config/joshuto/mimetype.toml
lrwxr-xr-x   1 ali  staff    59 Feb 23 00:03 preview_file.sh -> /Users/ali/.dotfiles/mackup/.config/joshuto/preview_file.sh
lrwxr-xr-x   1 ali  staff    54 Feb 23 00:03 theme.toml -> /Users/ali/.dotfiles/mackup/.config/joshuto/theme.toml
````
