### ISSUE TITLE
cd with tilde expansion

### ISSUE THREAD

**Issue by lahwaacz** [kamiyaa/joshuto#33]
I'd like to configure a shortcut for `:cd ~` to quickly go to my home directory, but the command fails with

    No such file or directory (os error 2)

**Comment by kamiyaa** [comment]
Apologies for not replying, I didn't notice this issue.

The current command line system is pretty scuffed.
Currently it doesn't do variable expansions and such.
This is mostly because it's complicated to get expansions to work while allowing for `:rename file name with space`

Ideally, there is a crate that does all this.
But I doubt there is one that allows for autocompletion on filenames with spaces.
So I predict there will be a lot of work to be done on the command line system (autocompletion, history, etc.)

**Comment by kamiyaa** [comment]
closed via https://github.com/kamiyaa/joshuto/pull/38
