### ISSUE TITLE
screen redraw after closing an outside window

### ISSUE THREAD

**Issue by muralikodali** [kamiyaa/joshuto#37]
I am using i3 window manager. After opening a file or image from joshuto and closing afterwards, screen display is not redrawn as shown below.

![screenshot_20201227143114](https://user-images.githubusercontent.com/11482766/103167403-f92d2100-4850-11eb-9a46-abd9b11ea395.png)

**Comment by kamiyaa** [comment]
Yes, this is a bug that I am aware of.
The current solution is to:
1. resize terminal
2. input some keys (which will trigger a redraw)
3. resize the terminal back
4. input more keys (which will trigger another redraw).

I'm not exactly sure how to implement this currently.
One thing that could be done is using [events()](https://docs.rs/termion/1.5.5/termion/input/trait.TermRead.html#tymethod.events) instead of [keys()](https://docs.rs/termion/1.5.5/termion/input/trait.TermRead.html#tymethod.keys).
This should give a wider range of input types, not just keystrokes.

But this is currently not of high priority to me, so it might take a while for me to get back to this.

**Comment by kamiyaa** [comment]
Should be implemented in e4faa16c8a7f2a51303ad3fe9f3891d8f7eabb82

**Comment by kamiyaa** [comment]
Feel free to re-open issue if still not working

**Comment by goderich** [comment]
I'm using version 0.9.0 from Archlinux's AUR (joshuto-git), and still encountering this issue with a tiling window manager.

**Comment by kamiyaa** [comment]
> I'm using version 0.9.0 from Archlinux's AUR (joshuto-git), and still encountering this issue with a tiling window manager.

Could you provide some more information and potentially a screenshot?
ie. before, after screenshots, what program/terminal/wm you were using, etc.

Thanks

**Comment by goderich** [comment]
Hi @kamiyaa , thanks for replying so quickly!

I am using bspwm as my WM, and alacritty as my terminal. Usually I run tmux too, but I tried joshuto in both, with the same results.
I don't know how to paste screenshots here (I don't think bspwm or any of my file managers do drag-and-drop), so here's an imgur link with the glitch in alacritty with and without tmux: https://imgur.com/a/SsosOvv

Please let me know what else I can do to help you help me.

**Comment by goderich** [comment]
OK, so I just upgraded my system and I don't seem to be experiencing it anymore (joshuto was not updated, mind). I don't know what happened. I'll keep you posted if this reappears.
