### ISSUE TITLE
Display file ownership (user and group)?

### ISSUE THREAD

**Issue by xfzv** [kamiyaa/joshuto#380]
I found https://github.com/kamiyaa/joshuto/commit/530973aea3fa46c469541bc291513a75e3aacd3e

However, I couldn't find anything related either in the documentation or in the built-in help menu to enable this.

Am I missing something?

Thanks.

**Comment by DLFW** [comment]
Hi,
I fear you're not missing anything. 

I guess there is currently no way to show user/group in Joshuto. The commit you've found is pretty old and the code has been moved around a lot since then. The meta-data still seems to be stored for each file, but not used anywhere in the UI.

I agree that it should be displayed in the status line.

Would be great if there would also be a line-mode showing user and permissions.

**Comment by kamiyaa** [comment]
@DLFW is correct.
I added those but haven't actually gotten around to actually implementing anything with it  :sweat_smile: 

Feel free to take a crack at it as I have been a bit busy with life atm :x

**Comment by kamiyaa** [comment]
Closing!
