### ISSUE TITLE
"Unknown error" when trying to move some elements to trash in a specific path

### ISSUE THREAD

**Issue by xfzv** [kamiyaa/joshuto#386]
I use Gentoo as my main distro but also have Arch Linux installed on another SSD, which is permanently mounted to `/media/Arch` via `/etc/fstab`.

When navigating to `/media/Arch/home/` (this dir + my actual user dir) with joshuto, I can create files/dirs just fine with ["ft"](https://github.com/kamiyaa/joshuto/blob/main/config/keymap.toml#L87) and ["mk"](https://github.com/kamiyaa/joshuto/blob/main/config/keymap.toml#L101), but I cannot move them to trash with either ["delete" or "dd"](https://github.com/kamiyaa/joshuto/blob/main/config/keymap.toml#L78-L79). I'm getting "Unknown error" printed at the bottom left corner of joshuto window.

I have other disks mounted to `/media/` (with correct permissions too) but couldn't reproduce the issue from these mount points. Both creating and moving files/dirs to trash work fine from there with joshuto.

Moving files from `/media/Arch/home/*` to trash with Dolphin works just fine as well.

Direct deletion with `use_trash = false` works as expected in `/media/Arch/home/*`.

**Comment by kamiyaa** [comment]
While this issue is known and documented, it shouldn't necessarily be a problem.
I can look into potential solutions

**Comment by kamiyaa** [comment]
With f9ebd1055b916532e307e1b64be296d74e760d0b

Instead of using a library, Joshuto now runs external commands to try and delete files.
`gio trash` will still fail because it does not support deleting on internally mounted filesystems.

However, you should be able to delete files from mount filesystems with the `trash-cli` command installed.
https://github.com/andreafrancia/trash-cli
