### ISSUE TITLE
Discord server

### ISSUE THREAD

**Issue by kamiyaa** [kamiyaa/joshuto#420]
Thinking of potentially creating a discord server where the community can discuss in a more casual setting. Would love to hear if this is something that people would find useful.

I probably won't have the capacity to manage and moderate the server, so will need to delegate that to someone.

**Comment by Beethoven-n** [comment]
i actually wouldn't mind participating. thing is, if i wanna be on a discord, i'd rather be somewhere with clearly set rules.
a lot of people don't understand that the rules are there to inform your community, rather than just to police them.
there should be a pretty hard and fast no "-ism" rule, to keep racists and transphobes from pushing pontential contributors away

**Comment by kamiyaa** [comment]
Added to readme
