### ISSUE TITLE
how to use cmd_aliases for command with user input?

### ISSUE THREAD

**Issue by xj-m** [kamiyaa/joshuto#452]
in `joshuto.toml` I configed 

```toml
[cmd_aliases]

j = "z"
```

Expected `j` could be used as same as `z`, but `cmd_aliases` was not able to take the shell input from user and used for zoxide.

Is there a way to replace a command?🙏

**Comment by eljamm** [comment]
Perhaps you can try remapping the `j` key in `keymap.toml`:

```toml
[default_view]

keymap = [
...
  { keys = ["j"], commands = [":z "] },
  { keys = ["j", "i"], commands = [":zi "] },
...
]
```

To do this, it's better to copy the [template keymap](https://github.com/kamiyaa/joshuto/blob/main/config/keymap.toml) to your config and modify it as necessary, since writing it from scratch might override your default keymaps, leaving them unmapped.
