### ISSUE TITLE
Failed to parse events! (`update:` issue with AUR package, normal build is fine)

### ISSUE THREAD

**Issue by inoshy** [kamiyaa/joshuto#91]
Hi, thanks for this awesome project! I really love this file explorer. 
I have run into an issue, I have no idea why. when I copied the `keymap.toml` from the repo to my joshuto config, it is giving me this output
```yaml
Failed to parse events: ["arrow_up"]
Failed to parse events: ["arrow_down"]
Unknown command: open
Unknown command: open
Unknown command: open
Unknown command: open_with
Failed to parse events: ["arrow_left"]
Unknown command: copy_filename_without_extension
Unknown command: copy_filepath
Unknown command: copy_dirname
sort: Unknown option ext
```

And the Up, Down, Left, Right keys are not working. but when I remove this config, those keys work fine! any idea why? thanks! :)

**Comment by inoshy** [comment]
Hi, an update. I fixed the issue by uninstalling the aur package and manually building it.  have no idea why the aur one was emitting those errors! 
I am enjoying joshuto. its the best file manager in existance.

**Comment by kamiyaa** [comment]
Glad you were able to fix the issue!
This is probably because the AUR has an older version.
I renamed some of the commands a while back to be more descriptive (`arrow_left` instead of just `left`, `open` instead of `open_file`)

Some of the other errors seem to be new features.
`copy_filename_without_extension`
`copy_filepath`
`copy_dirname`
`sort ext`
was only recently added.

Gonna close this issue now :)
Feel free to re-open if necessary

> **I swear it's the best file manager in existance.**

Wow, thanks! :heart: :heart:

**Comment by inoshy** [comment]
you are welcome kamiyaa! i just uninstalled thunar and adopted this. I can customize all the keybindings to my liking its so great of you! 😁
